export const NOTIFICATION_TYPE = {
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  RESERVATION_EXPIRING: 'RESERVATION_EXPIRING',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
