export const AUDIT_ACTION = {
  PARKING_SPACE_CREATED: 'PARKING_SPACE_CREATED',
  PARKING_SPACE_UPDATED: 'PARKING_SPACE_UPDATED',
  PARKING_SPACE_STATUS_UPDATED: 'PARKING_SPACE_STATUS_UPDATED',
  PARKING_SPACE_DELETED: 'PARKING_SPACE_DELETED',
  PARKING_SPACE_PHOTO_ADDED: 'PARKING_SPACE_PHOTO_ADDED',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  RESERVATION_EXTENDED: 'RESERVATION_EXTENDED',
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
} as const;

export const AUDIT_ENTITY = {
  PARKING_SPACE: 'ParkingSpace',
  RESERVATION: 'Reservation',
  PAYMENT: 'Payment',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
export type AuditEntity = (typeof AUDIT_ENTITY)[keyof typeof AUDIT_ENTITY];
